### PR TITLE
feat(person): store wedding and divorce dates

### LINKED ISSUE #178: Tracking of the weddings for a person
We have to record all the weddings for a person and to track the date(s) of the wedding(s) and the date(s) of the divorce(s).

### PR DESCRIPTION
**Pull request by jnizet**
fixes #178

### CODE REVIEW

**Comment by acrepet** [comment]
Strange : Wen I want to create a new person, I have this error : 

```
Une erreur technique inattendue s'est produite. Essayez de recharger la page. 
400 - Validation failed for object='personCommandDTO'. Error count: 1
```

**Comment by jnizet** [comment]
@acrepet good catch. Fixed in #223. The regexp validator used for the fiscal number accepts null values, but doesn't accept the empty string.

**Comment by acrepet** [comment]
Good fix! Could you merge #223 into the master and rebase this PR?

**Comment by jnizet** [comment]
Done.

**Comment by acrepet** [comment]
:+1:

**Comment by acrepet** [comment]
I've tested :+1:

**Pull request merged**
