### PR TITLE
Feat/spent time stats

### PR DESCRIPTION
**Pull request by jnizet**
Do not merge.

I don't even know if this is a useful feature or not. But I wanted to experiment with charts. 

Since this add chart.js to the app, it also adds ~110KB to the gzipped bundle (because it also add moment).

### CODE REVIEW

**Comment by jnizet** [comment]
Hah, the bad news is that, although it's useless for us, chart.js has a dependency on moment, which once again adds 50KB to the bundle for nothing.

**Comment by cexbrayat** [comment]
Yeah, we have the same in ng-ponyracer.
I saw your comment on the Charts.js issue 👍 

In the meantime, we could extract the tasks in a separate, lazy-loaded module after #142 .

**Comment by jnizet** [comment]
To be clear, for Globe, I don't mind much about the size of the bundle: there are only 5 or 6 users,  the app is not modified often, and it's used over a good network, on desktop browsers. So even if they have to load 500 KB every time the app is deployed, it's far from being a big deal.

**Comment by acrepet** [comment]
wahou I like it! I've tested it :+1: 
I think it could be very useful for Malika! Good job!

**Comment by jnizet** [comment]
OK, I'll merge then. It will at least avoid having to rebase continuously, and we will be able to demo it easily. If it really isn't useful, then we can remove it. If it has to be changed, it's not a big deal to have it partially implemented.

**Pull request merged**
