### PR TITLE
chore: bump to cli 1.3 and fix lint issues

### PR DESCRIPTION
**Pull request by cexbrayat**
`ng serve` now uses the proxyConf by default and can be run directly instead of `yarn start`.

### CODE REVIEW

**Comment by cexbrayat** [comment]
I added a commit to activate `--build-optimizer`:

Before:

262K 11 aoû 17:55 main.ab83cf637c3ec4a55a9a.bundle.js
843K 11 aoû 17:55 vendor.a4b859ed9242018fdec3.bundle.js
total 1105K

 38K 11 aoû 17:55 main.ab83cf637c3ec4a55a9a.bundle.js.gz
202K 11 aoû 17:55 vendor.a4b859ed9242018fdec3.bundle.js.gz
total 240K

with `--build-optimizer`:

994K 11 aoû 17:58 main.85d25df6a5e71acd8740.bundle.js

211K 11 aoû 17:58 main.85d25df6a5e71acd8740.bundle.js.gz

**Comment by cexbrayat** [comment]
@jnizet the build fails with a gradle error `Couldn't follow symbolic link` in `node_modules`, I have no idea why... Works on my machine, tell me if it's broken for you when you have the occasion...

**Comment by jnizet** [comment]
It fails on my machine too. I had to delete the node_modules directory to make it pass. So I guess the node_modules cache that we activated is causing this.

**Comment by jnizet** [comment]
I also notice the frontend build is even slower than before.
I remember the good old times of JS script kiddies making fun of Java for being slow and having a slow compile-deploy-run cycle. Now the backend is compiled, assembled, unit- and integration-tested before webpack even reaches half of just the build.

**Comment by jnizet** [comment]
I migrated to TS 2.4.2 in the next PR #96 and (hopefully) fixed the build issue. This PR LGTM, so if you're OK with the next one, you can just merge the next one.

**Comment by acrepet** [comment]
I had to delete the node_modules directory to make it pass too.

**Comment by jnizet** [comment]
merged as part of another PR. Closing.

**Pull request closed without merging**
