### PR TITLE
build: upgrade jacoco version in order to ignore generated code

### PR DESCRIPTION
**Pull request by jnizet**

### CODE REVIEW

**Comment by cexbrayat** [comment]
Does this fix the issue we have with kotlin data classes?

**Comment by jnizet** [comment]
It seems so, yes. I tested it locally and it seems to work fine. I'm waiting for the codecov report. I'm not sure I'll merge ths since the new version is the default version in the next gradle version, which is in RC.

**Comment by jnizet** [comment]
I expected a more significant improvement. But apparently, Codecov shows the "complexity coverage" by default (whatever that might mean). If we go into the details and look at the line coverage, we see an improvement. And the DTO files (data classes) like PersonDTO for example are now showing the actual coverage. See the chart:

capture d ecran 2018-11-05 a 20 13 39

The locally generated jacoco report is now more useful anyway, since it shows the actual coverage of the code now.

**Comment by jnizet** [comment]
Will wait for the next gradle release

**Pull request closed without merging**
