### PR TITLE
Fix/79 city editable

### PR DESCRIPTION
**Pull request by jnizet**

### CODE REVIEW

**Comment by acrepet** [comment]
I'm testing

**Comment by acrepet** [comment]
LGTM !

**Comment by jnizet** [comment]
Sorry guys. I've just amended this PR to make it even better (or so I hope). Can you please give it a look, before I merge everything?

**Comment by acrepet** [comment]
It's prefect! I've tested. Good idea to clear the city input on blur if not valid anymore !
LGTM !

**Pull request merged**
