### PR TITLE
chore: check js bundle sizes on buil

### PR DESCRIPTION
**Pull request by cexbrayat**
This uses [bundlesize](https://github.com/siddharthkp/bundlesize) to add a check on Travis about the bundle sizes (gzipped).

@jnizet This requires you to add a specific env variable on travis, check Slack for mre details.

### CODE REVIEW

**Comment by jnizet** [comment]
Environment variable added.

**Comment by cexbrayat** [comment]
I think I've now fixed the code coverage too https://codecov.io/gh/Ninja-Squad/globe42/tree/4c69915e753da17bfac05b096bc721134d628226

**Comment by jnizet** [comment]
@cexbrayat after rebasing, the check now fails because of the vendor bundle size, and almost because of the main bundle size. But

 - I didn't see anything suspicious in main. It's just that adding tasks made the bundle larger
 - The vendor bundle size increased because of moment, which adds all its locales, but everything seems normal too. 

Do we agree that we won't try to workaround moment's bundling problem just to gain a few bytes, and that this check was there only to warn us of something suspicious? And that we should just increase the limits before merging this PR?

**Comment by cexbrayat** [comment]
Feel free to increase as you see fit: I was just happy to see if it does the job. Looks like it does 👍

**Pull request merged**
