### PR TITLE
Fix/typos

### PR DESCRIPTION
**Pull request by jnizet**
fix typos detected by cedric when reviewing #67. I didn't amend that PR to avoid having to rebase everything that comes afterwards.

On top of #73

### CODE REVIEW

**Comment by jnizet** [comment]
Bizarre. None of the two builds benefitted from the cache: poms and jars were downloaded again, and npm and yarn were reinstalled.

**Comment by cexbrayat** [comment]
😞 Looks like it's a one cache per branch policy, with a fallback on the master branch's cache (that we don't have currently?)

**Comment by jnizet** [comment]
That doesn't fit well with our rebase strategy: every push on master has already been built before. Maybe we should just add a cron to travis to build master once every day or week?

**Comment by cexbrayat** [comment]
Why not. Do we need a cron? Isn't it possible to build master when a new commit is pushed on it?
That would be enough: the next PRs would use this cache I understand correctly

**Comment by cexbrayat** [comment]
Something like this maybe?

```
branches:
  only: 
    - master
```

**Pull request merged**
